# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='s@sergioe21.com', max_length=254),
        ),
        migrations.AddField(
            model_name='worker',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
