# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20160124_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='url_background',
            field=models.CharField(default='http://www.vallourec-ra2013.com/assets/img/background/background-univ-petrole-degrade.png', max_length=500),
        ),
    ]
